GET http://localhost:3000/auth/get/all

################################

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName": "Kyle",
    "lastName": "Metzen",
    "email": "lol2@lol.pl",
    "phoneNumber": "123123123",
    "password": "password"
}

###


POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "lol@lol.pl",
    "password": "password"
}

###
