GET http://localhost:3000/vehicles/get/all

################################

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName": "Kyle",
    "lastName": "Metzen",
    "email": "lol2@lol.pl",
    "phoneNumber": "123123123",
    "password": "password"
}

###


POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "lol@lol.pl",
    "password": "password"
}

###

GET http://localhost:3000/auth/validate
Authorization: Bearer <access_token>

################################

POST http://localhost:3000/auth/refresh/token
Content-Type: application/json

{
    "token": "<refresh_token>"
}

################################
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "token": "<refresh_token>"
}


##########################

POST http://localhost:3000/users/reservations/add
Content-Type: application/json

{
    "userId": 121,
    "vehicleId": 22,
    "duration": "+0 00:00:01"
}

################

GET http://localhost:3000/users/reservations/current?userId=121


###############

GET http://localhost:3000/users/stats?userId=121


################################################################
GET http://localhost:3000/vehicles/get/rented/user?userId=121

################################################################
POST http://localhost:3000/vehicles/update/position
Content-Type: application/json

{
    "vehicleId": 11,
    "lat": 50.01729,
    "lng": 19.9187
}